
const DAYS=["mandag","tirsdag","onsdag","torsdag","fredag","lørdag","søndag"];
const CATEGORIES=["Frukt og grønt","Kjøtt","Kjølevarer","Meieri","Frys","Hermetikk/halvfabrikat","Tørrvarer","Krydder","Glutenfritt","Bakevarer","Annet"];
let recipes=[],plan={},shoppingItems=[],customRecipes=JSON.parse(localStorage.getItem("middag_custom_recipes")||"{}"),activeImportId=null,activePickerDay=null,pendingAddRecipeId=null;
let appMeta={favorites:[],usageCounts:{},lastUsed:{},updatedAt:""},lastRemoteUpdatedAt="",syncTimer=null;
const $=id=>document.getElementById(id);
function normalize(s){return String(s||"").toLowerCase().normalize("NFD").replace(/[\u0300-\u036f]/g,"").trim()}
function capitalize(s){return s.charAt(0).toUpperCase()+s.slice(1)}
function recipeById(id){return recipes.find(r=>String(r.id)===String(id))}
function hasRecipe(r){return Boolean((r.ingredientsText&&r.ingredientsText.trim())||(r.instructions&&String(r.instructions).trim())||(r.structuredIngredients&&r.structuredIngredients.length))}
function getTags(r){const tags=new Set();if(Array.isArray(r.tags))r.tags.forEach(t=>tags.add(String(t).toLowerCase()));if(r.category)tags.add(String(r.category).toLowerCase());const text=normalize(`${r.name} ${r.category} ${r.ingredientsText||""} ${r.instructions||""}`);const rules=[["suppe",["suppe","soup","broth"]],["vegetar",["vegetar","veggie","tofu","linse","kikerter","aubergine"]],["kylling",["kylling","chicken"]],["pasta",["pasta","spaghetti","orzo","tagliatelle","fettuccine"]],["salat",["salat","salad"]],["taco",["taco","wrap","fajita"]],["airfryer",["airfryer","air fryer"]],["fisk",["fisk","shrimp","reker","scampi","ørret","laks"]],["glutenfritt",["glutenfri","gluten free"]],["rask",["15 minute","20 minute","rask","enkel"]],["asiatisk",["soy","soya","sesam","gochujang","thai","ramen","noodle","nudler"]],["indisk",["indisk","curry","masala","butter chicken"]]];for(const[tag,words]of rules)if(words.some(w=>text.includes(normalize(w))))tags.add(tag);return[...tags].slice(0,10)}
function enrichTags(r){const tags=new Set(getTags(r));const text=normalize(`${r.name} ${r.category} ${r.ingredientsText||""} ${r.instructions||""}`);if(text.includes("glutenfri"))tags.add("glutenfritt");return[...tags]}
function emojiForRecipe(r){if(r.emoji)return r.emoji;const t=normalize(`${r.name} ${r.category} ${enrichTags(r).join(" ")}`);if(t.includes("suppe"))return"🍲";if(t.includes("salat"))return"🥗";if(t.includes("pasta")||t.includes("spaghetti"))return"🍝";if(t.includes("taco")||t.includes("wrap")||t.includes("fajita"))return"🌮";if(t.includes("pizza"))return"🍕";if(t.includes("kylling"))return"🍗";if(t.includes("fisk")||t.includes("shrimp")||t.includes("scampi"))return"🍤";if(t.includes("biff")||t.includes("kjøtt"))return"🥩";if(t.includes("ramen")||t.includes("nudler")||t.includes("noodle"))return"🍜";if(t.includes("curry")||t.includes("indisk"))return"🍛";if(t.includes("airfryer"))return"🔥";if(t.includes("vegetar"))return"🥦";return"🍽️"}
function mergeCustomData(){recipes=recipes.map(r=>({...r,...(customRecipes[r.id]||{})}))}
async function init(){const rr=await fetch("/api/recipes").then(r=>r.json());recipes=rr.recipes||[];mergeCustomData();const pr=await fetch("/api/plan").then(r=>r.json()).catch(()=>({plan:{}}));const raw=pr.plan?.items||pr.plan||{};plan=migratePlan(raw);shoppingItems=pr.plan?.shoppingItems||[];appMeta=pr.plan?.meta||appMeta;lastRemoteUpdatedAt=pr.plan?.updatedAt||"";fillDaySelectors();fillAddToDaySelect();$("recipeCount").textContent=`${recipes.length} oppskrifter`;["createDaysBtn","generateListBtn","resetShoppingBtn","resetPlanBtn","resetPlanInlineBtn","recipeSearch","recipeSort","addRecipeBtn","parseCaptionBtn","saveParsedBtn","aiParseCaptionBtn","randomWeekBtn","aiWeekBtn","confirmAddToDayBtn","pickerSearch","cleanupRecipesBtn"].forEach(id=>{const el=$(id);if(!el)return;const f={createDaysBtn:createDayRows,generateListBtn:generateShoppingList,resetShoppingBtn:resetShoppingList,resetPlanBtn:resetPlan,resetPlanInlineBtn:resetPlan,recipeSearch:renderRecipeResults,recipeSort:renderRecipeResults,addRecipeBtn:openAddRecipe,parseCaptionBtn:parseCaption,saveParsedBtn:saveParsedRecipe,aiParseCaptionBtn:parseCaptionAI,randomWeekBtn:randomWeek,aiWeekBtn:smartWeek,confirmAddToDayBtn:confirmAddToDay,pickerSearch:renderPickerResults,cleanupRecipesBtn:cleanupVisibleRecipes}[id];el.addEventListener(id==="recipeSearch"||id==="pickerSearch"||id==="recipeSort"?"input":"click",f)});if($("recipeSort"))$("recipeSort").addEventListener("change",renderRecipeResults);if($("readScreenshotsBtn"))$("readScreenshotsBtn").addEventListener("click",readScreenshotsWithOCR);if($("clearCaptionBtn"))$("clearCaptionBtn").addEventListener("click",()=>{$("captionInput").value="";window.lastAiParsedRecipe=null});document.querySelectorAll(".nav-btn").forEach(btn=>btn.addEventListener("click",()=>showView(btn.dataset.view)));createDayRows();renderRecipeResults();renderShoppingList(shoppingItems);startRealtimeSync()}
function migratePlan(raw){const out={};for(const d of DAYS){const v=raw?.[d];out[d]=Array.isArray(v)?v:(v?[{type:"recipe",recipeId:v}]:[])}return out}
function showView(v){document.querySelectorAll(".view").forEach(x=>x.classList.toggle("active",x.id===v));document.querySelectorAll(".nav-btn").forEach(b=>b.classList.toggle("active",b.dataset.view===v))}
function fillDaySelectors(){for(const id of["startDay","endDay"])$(id).innerHTML=DAYS.map(d=>`<option value="${d}">${capitalize(d)}</option>`).join("");$("startDay").value="mandag";$("endDay").value="fredag"}
function fillAddToDaySelect(){if($("addToDaySelect"))$("addToDaySelect").innerHTML=selectedDays().map(d=>`<option value="${d}">${capitalize(d)}</option>`).join("")}
function selectedDays(){const s=DAYS.indexOf($("startDay").value),e=DAYS.indexOf($("endDay").value),out=[];let i=s;while(true){out.push(DAYS[i]);if(i===e)break;i=(i+1)%DAYS.length}return out}
function setLiveStatus(t,cls=""){const el=$("liveStatus");if(!el)return;el.textContent="● "+t;el.className="live-status"+(cls?` ${cls}`:"")}
function savePlan(){appMeta.updatedAt=new Date().toISOString();localStorage.setItem("middag_plan",JSON.stringify(plan));fetch("/api/plan",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({plan:{items:plan,shoppingItems,meta:appMeta,updatedAt:appMeta.updatedAt}})}).catch(e=>{console.warn(e);setLiveStatus("Sync-feil","error")})}
function startRealtimeSync(){if(syncTimer)clearInterval(syncTimer);syncTimer=setInterval(syncFromServer,5000);setLiveStatus("Live")}
async function syncFromServer(){try{setLiveStatus("Syncer","syncing");const pr=await fetch("/api/plan").then(r=>r.json());const remote=pr.plan?.updatedAt||"";if(remote&&remote!==lastRemoteUpdatedAt&&remote!==appMeta.updatedAt){plan=migratePlan(pr.plan?.items||{});shoppingItems=pr.plan?.shoppingItems||shoppingItems;appMeta=pr.plan?.meta||appMeta;lastRemoteUpdatedAt=remote;createDayRows();renderShoppingList(shoppingItems);renderRecipeResults()}const rr=await fetch("/api/recipes").then(r=>r.json());if(rr.recipes&&rr.recipes.length!==recipes.length){recipes=rr.recipes;mergeCustomData();renderRecipeResults();createDayRows()}setLiveStatus("Live")}catch(e){setLiveStatus("Offline?","error")}}
function resetPlan(){if(!confirm("Nullstille ukeplanen?"))return;plan={};for(const d of DAYS)plan[d]=[];savePlan();createDayRows()}
function resetShoppingList(){if(!confirm("Nullstille handlelisten?"))return;shoppingItems=[];savePlan();renderShoppingList(shoppingItems)}
function createDayRows(){const c=$("dayRows"),days=selectedDays();fillAddToDaySelect();for(const d of days)if(!Array.isArray(plan[d]))plan[d]=[];c.innerHTML="";for(const day of days){const card=document.createElement("div");card.className="day-row day-card-v16";card.innerHTML=`<div class="day-head-v16"><h3>${day}</h3><button class="ghost" data-picker="${day}">+ Oppskrift</button></div><input class="day-text-input" data-free="${day}" placeholder="Skriv rett manuelt, f.eks. Grillmat"><div class="day-actions-row"><button class="ghost" data-addtext="${day}">+ Legg til tekstrett</button><button class="ghost" data-clear="${day}">Tøm dag</button></div><div class="day-items"></div>`;c.appendChild(card);card.querySelector("[data-picker]").addEventListener("click",()=>openRecipePicker(day));card.querySelector("[data-addtext]").addEventListener("click",()=>addFreeTextToDay(day,card.querySelector("[data-free]").value));card.querySelector("[data-clear]").addEventListener("click",()=>{plan[day]=[];savePlan();createDayRows()});renderDayItems(card,day)}}
function renderDayItems(card,day){const box=card.querySelector(".day-items"),items=plan[day]||[];if(!items.length){box.innerHTML=`<div class="empty-state">Ingen retter lagt til.</div>`;return}box.innerHTML=items.map((item,idx)=>{if(item.type==="text")return`<div class="plan-item"><div><div class="plan-item-title">✍️ ${escapeHtml(item.text)}</div><div class="plan-item-meta">Manuell rett – legg varer manuelt i handlelisten</div></div><button class="remove-btn" onclick="removePlanItem('${day}',${idx})">×</button></div>`;const r=recipeById(item.recipeId),title=r?`${emojiForRecipe(r)} ${r.name}`:"Oppskrift ikke funnet",meta=r?`${r.category||"Ukjent"} · brukt ${usageCount(r.id)}× · ${hasRecipe(r)?"oppskrift funnet":"mangler oppskrift"}`:"";return`<div class="plan-item"><div><div class="plan-item-title">${escapeHtml(title)}</div><div class="plan-item-meta">${escapeHtml(meta)}</div></div><button class="remove-btn" onclick="removePlanItem('${day}',${idx})">×</button></div>`}).join("")}
window.removePlanItem=(day,idx)=>{plan[day].splice(idx,1);savePlan();createDayRows()}
function addFreeTextToDay(day,text){const t=String(text||"").trim();if(!t)return;plan[day].push({type:"text",text:t});savePlan();createDayRows()}
function openRecipePicker(day){activePickerDay=day;$("pickerSearch").value="";renderPickerResults();$("recipePickerDialog").showModal()}
function renderPickerResults(){const q=normalize($("pickerSearch").value);const f=recipes.filter(r=>!q||searchableText(r).includes(q)).sort((a,b)=>a.name.localeCompare(b.name,"no")).slice(0,300);$("pickerResults").innerHTML=f.map(r=>`<div class="recipe-card" onclick="addRecipeToDay('${activePickerDay}','${escapeAttr(r.id)}')"><div class="recipe-thumb recipe-emoji">${emojiForRecipe(r)}</div><div><strong>${escapeHtml(r.name)}</strong><div class="recipe-meta">${escapeHtml(r.category||"Ukjent")} · ${hasRecipe(r)?"✅":"🟡"}</div></div><button type="button" class="ghost">Legg til</button></div>`).join("")}
window.addRecipeToDay=(day,id)=>{plan[day].push({type:"recipe",recipeId:id});bumpUsage(id);savePlan();createDayRows();renderRecipeResults();$("recipePickerDialog").close()}
function openAddRecipe(){const id=`custom-${Date.now()}`;recipes.push({id,name:"Ny oppskrift",category:"Annet",source:"Manuell",link:"",ingredientsText:"",instructions:"",tags:[]});activeImportId=id;$("importTarget").textContent="Lagrer som ny oppskrift";$("importLinkWrap").innerHTML="Legg inn navn, lenke og caption/oppskriftstekst.";$("importName").value="";$("importLink").value="";$("importCategory").value="Annet";$("importServings").value="";$("captionInput").value="";$("parsedIngredients").value="";$("parsedInstructions").value="";window.lastAiParsedRecipe=null;$("importDialog").showModal()}
function openImport(id){activeImportId=id;const r=recipeById(id);$("importTarget").textContent=`Lagrer på: ${r.name}`;$("importLinkWrap").innerHTML=r.link?`Kilde: <a href="${escapeAttr(r.link)}" target="_blank" rel="noopener">åpne originaloppskrift</a>`:"Ingen kilde registrert";$("importName").value=r.name||"";$("importLink").value=r.link||"";$("importCategory").value=r.category||"Annet";$("importServings").value=r.servings||"";$("captionInput").value="";$("parsedIngredients").value=ingredientsToText(r);$("parsedInstructions").value=instructionsToText(r);window.lastAiParsedRecipe=null;$("importDialog").showModal()}
async function parseCaptionAI(){const caption=$("captionInput").value.trim(),status=$("aiStatus"),btn=$("aiParseCaptionBtn"),r=recipeById(activeImportId)||{};if(!caption)return alert("Lim inn caption/oppskriftstekst først.");try{btn.disabled=true;btn.textContent="AI parser …";status.textContent="Sender tekst til AI-parser …";const res=await fetch("/api/parse-caption",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({caption,recipeName:$("importName").value.trim()||r.name||"",sourceUrl:$("importLink").value.trim()||r.link||"",category:$("importCategory").value||r.category||""})});const data=await res.json();if(!data.ok)throw new Error(data.error||"AI-parser feilet");const p=data.parsed||{};$("importName").value=$("importName").value.trim()||p.title||r.name||"";$("importCategory").value=p.category||$("importCategory").value||"Annet";$("importServings").value=p.servings||$("importServings").value||"";$("parsedIngredients").value=(p.ingredients||[]).map(formatAiIngredient).join("\n");$("parsedInstructions").value=(p.instructions||[]).map((s,i)=>`${i+1}. ${s}`).join("\n");p.tags=enrichTags({...r,...p,name:p.title||$("importName").value});p.emoji=emojiForRecipe({...r,...p,name:p.title||$("importName").value});window.lastAiParsedRecipe=p;status.textContent=`AI-parsing ferdig. Tags: ${(p.tags||[]).join(", ")}`}catch(err){status.textContent="AI-parser feilet: "+(err?.message||err);alert("AI-parser feilet. Se statusfelt.")}finally{btn.disabled=false;btn.textContent="AI-parse caption"}}
function formatAiIngredient(ing){if(typeof ing==="string")return ing;const amount=ing.amount||"",unit=ing.unit||"",item=ing.item||"",note=ing.note?` (${ing.note})`:"",cat=ing.shoppingCategory?` [${ing.shoppingCategory}]`:"";return`${amount} ${unit} ${item}${note}${cat}`.replace(/\s+/g," ").trim()}
function parseCaption(){const text=$("captionInput").value.trim(),lines=text.split(/\r?\n/).map(l=>l.trim()).filter(Boolean),ing=[],inst=[];let mode="";for(const line of lines){if(/ingredients|ingredienser/i.test(line)){mode="ing";continue}if(/instructions|method|fremgangsmåte|slik gjør/i.test(line)){mode="inst";continue}if(mode==="inst"||/^\d+[\.)]/.test(line))inst.push(line);else if(mode==="ing"||/^[-*•]?\s*[\d¼½¾]/.test(line))ing.push(convertIngredientLine(line.replace(/^[-*•]\s*/,"")))}$("parsedIngredients").value=ing.join("\n");$("parsedInstructions").value=inst.join("\n")}
async function saveParsedRecipe(){if(!activeImportId)return alert("Ingen oppskrift valgt.");const name=$("importName").value.trim()||"Ny oppskrift",link=$("importLink").value.trim(),category=$("importCategory").value||"Annet",ai=window.lastAiParsedRecipe||{},base=recipeById(activeImportId)||{};const patch={name,link,category,source:link.includes("instagram")?"Instagram":link.includes("tiktok")?"TikTok":link?"Nettside":"Manuell",servings:$("importServings").value.trim(),ingredientsText:$("parsedIngredients").value.trim(),instructions:$("parsedInstructions").value.trim(),structuredIngredients:ai.ingredients||[],structuredInstructions:ai.instructions||[],tags:ai.tags||enrichTags({...base,name,category,ingredientsText:$("parsedIngredients").value,instructions:$("parsedInstructions").value}),emoji:ai.emoji||emojiForRecipe({...base,name,category}),aiParsed:!!window.lastAiParsedRecipe,aiConfidence:ai.confidence||"",status:"Fullført",manualCheck:"Nei",updatedAt:new Date().toISOString()};const idx=recipes.findIndex(r=>String(r.id)===String(activeImportId));if(idx>=0)recipes[idx]={...recipes[idx],...patch};else recipes.push({id:activeImportId,...patch});try{const response=await fetch("/api/save-recipe",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({id:activeImportId,patch})});const saveResult=await response.json().catch(()=>({}));if(!response.ok||saveResult.ok===false)throw new Error(saveResult.error||"Lagring feilet");$("importDialog").close();createDayRows();renderRecipeResults();alert("Oppskriften er lagret permanent i Supabase ✅")}catch(err){customRecipes[activeImportId]={...(customRecipes[activeImportId]||{}),...patch};localStorage.setItem("middag_custom_recipes",JSON.stringify(customRecipes));alert("Oppskriften vises nå i denne nettleseren, men Supabase-lagring feilet: "+(err?.message||err))}}
function generateShoppingList(){const days=selectedDays(),list=[];for(const day of days){for(const item of(plan[day]||[])){if(item.type==="text")continue;const r=recipeById(item.recipeId);if(!r||!hasRecipe(r))continue;for(const line of extractIngredientLines(r))list.push({text:line,category:categorize(line),recipe:r.name,done:false})}}shoppingItems=list;renderShoppingList(shoppingItems);savePlan();showView("viewShopping")}
function renderShoppingList(items){const grouped=Object.fromEntries(CATEGORIES.map(c=>[c,[]]));for(const item of items){if(!grouped[item.category])grouped[item.category]=[];grouped[item.category].push(item)}$("shoppingList").innerHTML=CATEGORIES.map(cat=>{const arr=grouped[cat]||[];return`<div class="category" data-category="${escapeAttr(cat)}"><div class="category-head"><h3>${cat}</h3><button class="tiny-add" onclick="addCustomShoppingItem('${escapeAttr(cat)}')">+ Legg til</button></div><div class="category-items">${arr.length?arr.map(it=>shoppingItemHtml(it)).join(""):`<p class="hint small-hint">Ingen varer enda.</p>`}</div></div>`}).join("")}
function shoppingItemHtml(it){return`<div class="item"><input type="checkbox" ${it.done?"checked":""} onchange="this.closest('.item').classList.toggle('done', this.checked)"><input type="text" value="${escapeAttr(it.text)}" title="Fra: ${escapeAttr(it.recipe||'Egen vare')}"><button class="remove-btn" title="Fjern" onclick="this.closest('.item').remove()">×</button></div>`}
window.addCustomShoppingItem=function(category){const text=prompt(`Legg til vare i ${category}:`);if(!text||!text.trim())return;shoppingItems.push({text:text.trim(),category,recipe:"Egen vare",done:false});renderShoppingList(shoppingItems);savePlan()}
function renderRecipeResults(){const q=normalize($("recipeSearch").value),sort=$("recipeSort")?.value||"az";let filtered=recipes.filter(r=>!q||searchableText(r).includes(q));filtered=sortRecipes(filtered,sort);$("recipeResults").innerHTML=filtered.map(r=>recipeCardHtml(r)).join("")||`<div class="empty-state">Ingen oppskrifter funnet.</div>`}
function sortRecipes(arr,sort){const copy=[...arr];if(sort==="za")return copy.sort((a,b)=>b.name.localeCompare(a.name,"no"));if(sort==="category")return copy.sort((a,b)=>`${a.category||""} ${a.name}`.localeCompare(`${b.category||""} ${b.name}`,"no"));if(sort==="used")return copy.sort((a,b)=>usageCount(b.id)-usageCount(a.id)||a.name.localeCompare(b.name,"no"));if(sort==="favorites")return copy.sort((a,b)=>Number(isFavorite(b.id))-Number(isFavorite(a.id))||a.name.localeCompare(b.name,"no"));if(sort==="recent")return copy.sort((a,b)=>String(appMeta.lastUsed?.[b.id]||b.updatedAt||b.createdAt||"").localeCompare(String(appMeta.lastUsed?.[a.id]||a.updatedAt||a.createdAt||"")));if(sort==="tags")return copy.sort((a,b)=>enrichTags(a).join(",").localeCompare(enrichTags(b).join(","),"no")||a.name.localeCompare(b.name,"no"));if(sort==="missing")return copy.sort((a,b)=>Number(hasRecipe(a))-Number(hasRecipe(b))||a.name.localeCompare(b.name,"no"));return copy.sort((a,b)=>a.name.localeCompare(b.name,"no"))}
function recipeCardHtml(r){const tags=enrichTags(r),fav=isFavorite(r.id)?"★":"☆";return`<div class="recipe-card" onclick="openRecipeDetails('${escapeAttr(r.id)}')"><div class="recipe-thumb recipe-emoji">${emojiForRecipe(r)}</div><div><div class="recipe-topline"><strong>${escapeHtml(r.name)}</strong><button class="favorite-btn" onclick="event.stopPropagation();toggleFavorite('${escapeAttr(r.id)}')" title="Favoritt">${fav}</button></div><div class="recipe-meta">${escapeHtml(r.category||"Ukjent")} · ${hasRecipe(r)?"✅ Oppskrift funnet":"🟡 Mangler oppskrift"} · brukt ${usageCount(r.id)}× · ${escapeHtml(r.source||"")}</div><div class="recipe-tags">${tags.slice(0,6).map(t=>`<span class="tag">${escapeHtml(t)}</span>`).join("")}</div><div class="recipe-meta recipe-actions">${r.link?`<a href="${escapeAttr(r.link)}" target="_blank" rel="noopener" onclick="event.stopPropagation()">Åpne kilde</a>`:"Ingen lenke"} · <button class="link-button" onclick="event.stopPropagation();openImport('${escapeAttr(r.id)}')">${hasRecipe(r)?"Rediger":"Importer"}</button></div></div></div>`}
window.openRecipeDetails=function(id){const r=recipeById(id);if(!r)return;$("recipeDialogTitle").textContent=`${emojiForRecipe(r)} ${r.name}`;const tags=enrichTags(r);$("recipeDialogBody").innerHTML=`<p class="recipe-meta">${escapeHtml(r.category||"Ukjent")} · ${escapeHtml(r.source||"")} · brukt ${usageCount(r.id)}×</p><div class="recipe-tags">${tags.map(t=>`<span class="tag">${escapeHtml(t)}</span>`).join("")}</div><div class="inline-actions"><button type="button" class="favorite-btn" onclick="toggleFavorite('${escapeAttr(r.id)}')">${isFavorite(r.id)?"★ Favoritt":"☆ Favoritt"}</button><button type="button" class="primary" onclick="openAddToDay('${escapeAttr(r.id)}')">+ Legg til i ukesmeny</button><button type="button" class="ghost" onclick="openImport('${escapeAttr(r.id)}');document.getElementById('recipeDialog').close();">Rediger</button>${r.link?`<a class="source-link-inline" href="${escapeAttr(r.link)}" target="_blank" rel="noopener">Åpne kilde</a>`:""}</div><div class="recipe-detail-section"><h3>Ingredienser</h3>${formatList(ingredientsToText(r))}</div><div class="recipe-detail-section"><h3>Fremgangsmåte</h3>${formatSteps(instructionsToText(r))}</div>`;$("recipeDialog").showModal()}
window.openAddToDay=function(id){pendingAddRecipeId=id;const r=recipeById(id);$("addToDayRecipeName").textContent=r?.name||"";fillAddToDaySelect();$("addToDayDialog").showModal()}
function confirmAddToDay(){const day=$("addToDaySelect").value;if(!day||!pendingAddRecipeId)return;plan[day].push({type:"recipe",recipeId:pendingAddRecipeId});bumpUsage(pendingAddRecipeId);savePlan();createDayRows();renderRecipeResults();$("addToDayDialog").close();$("recipeDialog").close();showView("viewPlan")}
function randomWeek(){const days=selectedDays(),usable=recipes.filter(hasRecipe);for(const day of days){const r=usable[Math.floor(Math.random()*usable.length)];plan[day]=r?[{type:"recipe",recipeId:r.id}]:[];if(r)bumpUsage(r.id)}savePlan();createDayRows();renderRecipeResults()}
async function smartWeek(){const prompt=$("smartPrompt").value.trim(),days=selectedDays();$("smartStatus").textContent="Lager AI-forslag …";try{const payloadRecipes=recipes.filter(hasRecipe).map(r=>({id:r.id,name:r.name,category:r.category,tags:enrichTags(r),favorite:isFavorite(r.id),usage:usageCount(r.id)}));const res=await fetch("/api/smart-week",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({prompt,days,recipes:payloadRecipes})});const data=await res.json();if(!data.ok)throw new Error(data.error||"AI-ukemeny feilet");const items=data.plan?.items||[];for(const day of days)plan[day]=[];for(const row of items){const day=String(row.day||"").toLowerCase();if(!DAYS.includes(day))continue;const ids=row.recipeIds||row.recipe_ids||[];plan[day]=ids.filter(id=>recipeById(id)).map(id=>{bumpUsage(id);return{type:"recipe",recipeId:id}});if(row.note&&!plan[day].length)plan[day]=[{type:"text",text:row.note}]}$("smartStatus").textContent="AI-forslag laget. Du kan justere manuelt.";savePlan();createDayRows();renderRecipeResults()}catch(e){$("smartStatus").textContent="AI feilet, bruker lokal smart velger.";localSmartWeek()}}
function localSmartWeek(){const p=normalize($("smartPrompt").value),days=selectedDays();let pool=recipes.filter(hasRecipe);if(p.includes("vegetar"))pool=pool.filter(r=>enrichTags(r).includes("vegetar")||normalize(r.category).includes("vegetar"));if(p.includes("suppe"))pool=pool.filter(r=>enrichTags(r).includes("suppe"));if(p.includes("kylling"))pool=pool.filter(r=>enrichTags(r).includes("kylling"));if(p.includes("rask"))pool=pool.filter(r=>enrichTags(r).includes("rask"));if(pool.length<days.length)pool=recipes.filter(hasRecipe);for(const day of days){const r=pool[Math.floor(Math.random()*pool.length)];plan[day]=r?[{type:"recipe",recipeId:r.id}]:[];if(r)bumpUsage(r.id)}savePlan();createDayRows();renderRecipeResults()}
function usageCount(id){return Number(appMeta.usageCounts?.[id]||0)}
function bumpUsage(id){if(!id)return;appMeta.usageCounts=appMeta.usageCounts||{};appMeta.lastUsed=appMeta.lastUsed||{};appMeta.usageCounts[id]=Number(appMeta.usageCounts[id]||0)+1;appMeta.lastUsed[id]=new Date().toISOString()}
function isFavorite(id){return(appMeta.favorites||[]).includes(id)}
function toggleFavorite(id){appMeta.favorites=appMeta.favorites||[];if(isFavorite(id))appMeta.favorites=appMeta.favorites.filter(x=>x!==id);else appMeta.favorites.push(id);savePlan();renderRecipeResults();if($("recipeDialog")?.open)openRecipeDetails(id)}
window.toggleFavorite=toggleFavorite
function searchableText(r){return normalize(`${r.name} ${r.category} ${r.source} ${r.status} ${enrichTags(r).join(" ")} ${r.ingredientsText||""}`)}
function ingredientsToText(r){if(r.ingredientsText)return r.ingredientsText;if(Array.isArray(r.structuredIngredients)&&r.structuredIngredients.length)return r.structuredIngredients.map(formatAiIngredient).join("\n");return""}
function instructionsToText(r){if(r.instructions)return Array.isArray(r.instructions)?r.instructions.join("\n"):String(r.instructions);if(Array.isArray(r.structuredInstructions))return r.structuredInstructions.map((x,i)=>`${i+1}. ${x}`).join("\n");return""}
function formatList(text){const lines=String(text||"").split(/\n|;/).map(x=>x.trim()).filter(Boolean);if(!lines.length)return`<p class="hint">Ingen ingredienser lagt inn.</p>`;return`<ul>${lines.map(l=>`<li>${escapeHtml(l)}</li>`).join("")}</ul>`}
function formatSteps(text){const lines=String(text||"").split(/\n/).map(x=>x.trim()).filter(Boolean);if(!lines.length)return`<p class="hint">Ingen fremgangsmåte lagt inn.</p>`;return`<ol>${lines.map(l=>`<li>${escapeHtml(l.replace(/^\d+[\.)]\s*/,""))}</li>`).join("")}</ol>`}
function extractIngredientLines(r){return ingredientsToText(r).split(/;|\n/).map(s=>convertIngredientLine(s.replace(/\s*\[[^\]]+\]\s*$/,"").trim())).filter(s=>s.length>1)}
function categorize(line){const s=normalize(line);const spice=["salt","pepper","oregano","basilikum","basil","gochugaru","paprika","spisskummen","cumin","kanel","chili flakes","chiliflak","curry powder","karri","garam masala","laurbær","sesamfrø","sesame seeds","sukker","sugar","honning","honey"];if(spice.some(w=>s.includes(normalize(w))))return"Krydder";const dry=["soy sauce","soyasaus","soya","tamari","sesamolje","sesame oil","olivenolje","olive oil","olje","oil","riseddik","rice vinegar","vinegar","eddik","sriracha","hot sauce","fish sauce","fiskesaus","stock","kraft","broth","buljong","peanøttsmør","peanut butter","tomatpure","tomato paste"];if(dry.some(w=>s.includes(normalize(w))))return"Tørrvarer";const map=[["Kjøtt",["kylling","chicken","biff","beef","okse","kjøttdeig","svin","pork","kotelett","pølse","sausage","kalkun","bacon"]],["Meieri",["melk","milk","fløte","cream","rømme","ost","cheese","parmesan","feta","cottage cheese","yoghurt","smør","butter"]],["Frys",["frossen","frosne","frozen","edamame"]],["Hermetikk/halvfabrikat",["boks","can ","canned","kokosmelk","coconut milk","kidney","kikerter","chickpeas","diced tomatoes","hakkede tomater","bønner","beans"]],["Tørrvarer",["pasta","nudler","noodles","ris","rice","orzo","bulgur","quinoa","mel","flour","breadcrumbs"]],["Glutenfritt",["glutenfri","gluten free"]],["Bakevarer",["brød","bread","pita","tortilla","burgerbrød","wrap"]],["Frukt og grønt",["agurk","cucumber","gulrot","carrot","løk","onion","hvitløk","garlic","ingefær","ginger","potet","potato","søtpotet","sweet potato","squash","zucchini","tomat","tomato","paprika","pepper","sopp","mushroom","brokkoli","broccoli","blomkål","cauliflower","kål","cabbage","spinat","spinach","salat","lettuce","lime","sitron","lemon","koriander","cilantro","persille","parsley","selleri","celery","avokado","avocado","aubergine","eggplant","chili","vårløk","spring onion"]]];for(const[cat,words]of map)if(words.some(w=>s.includes(normalize(w))))return cat;if(s.includes("tofu"))return"Kjølevarer";return"Annet"}
function convertIngredientLine(line){let s=String(line||"").trim();s=s.replace(/(\d+(?:[.,]\d+)?)\s*cups?\b/gi,(_,n)=>`${String(Math.round(parseFloat(n.replace(",","."))*24)/10).replace(".",",")} dl`);s=s.replace(/(\d+(?:[.,]\d+)?)\s*(tbsp|tablespoons?)\b/gi,"$1 ss");s=s.replace(/(\d+(?:[.,]\d+)?)\s*(tsp|teaspoons?)\b/gi,"$1 ts");s=s.replace(/(\d+(?:[.,]\d+)?)\s*(oz|ounces?)\b/gi,(_,n)=>`${Math.round(parseFloat(n.replace(",","."))*28.35)} g`);return s}
async function cleanupVisibleRecipes(){if(!confirm("Rydde tags, emoji og norske mål for oppskriftene?"))return;const btn=$("cleanupRecipesBtn");if(btn){btn.disabled=true;btn.textContent="Rydder …"}let updated=0;for(const r of recipes){const patch={tags:enrichTags(r),emoji:emojiForRecipe(r),ingredientsText:ingredientsToText(r).split(/\n/).map(convertIngredientLine).join("\n"),updatedAt:new Date().toISOString()};try{const response=await fetch("/api/save-recipe",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({id:r.id,patch})});const data=await response.json().catch(()=>({}));if(response.ok&&data.ok!==false){Object.assign(r,patch);updated++}}catch(e){console.warn("rydd feilet",r.name,e)}}renderRecipeResults();createDayRows();if(btn){btn.disabled=false;btn.textContent="Rydd tags/mål"}alert(`Ryddet ${updated} oppskrifter. Kategorisering av handleliste er forbedret.`)}
async function readScreenshotsWithOCR(){const input=$("screenshotInput"),files=Array.from(input?.files||[]),status=$("ocrStatus");if(!files.length)return alert("Velg ett eller flere skjermbilder først.");if(!window.Tesseract)return alert("OCR-biblioteket ble ikke lastet.");status.textContent=`Leser ${files.length} bilde(r) …`;const chunks=[];for(let i=0;i<files.length;i++){status.textContent=`OCR bilde ${i+1}/${files.length}`;const result=await Tesseract.recognize(files[i],"eng");if(result?.data?.text)chunks.push(result.data.text.trim())}$("captionInput").value=[$("captionInput").value.trim(),chunks.join("\n\n")].filter(Boolean).join("\n\n");status.textContent="Ferdig. Se over teksten og trykk AI-parse caption."}
function escapeHtml(s){return String(s??"").replace(/[&<>"]/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;"}[m]))}
function escapeAttr(s){return escapeHtml(s).replace(/'/g,"&#39;")}
init();
